{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\fusion\\snapshots\\DOS-BL-MBR-2\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1666589895.9731817
        },
        "01 program-started": {
            "timestamp": 1666589929.0555704
        },
        "02 program-loaded": {
            "timestamp": 1666589930.8475711
        },
        "03 program-prepared": {
            "timestamp": 1666589936.5263057,
            "screenshot": true,
            "snapshot": true
        },
        "05 model-not-loaded": {
            "timestamp": 1666589949.9951148,
            "screenshot": true,
            "snapshot": true,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        },
        "06 program-stopped": {
            "timestamp": 1666589976.0371187
        }
    }
}