{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\fusion\\snapshots\\DOS-FUZ-LIB3MF\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1665900956.1894016
        },
        "01 program-started": {
            "timestamp": 1665900988.005306
        },
        "02 program-loaded": {
            "timestamp": 1665900989.6072555
        },
        "03 program-prepared": {
            "timestamp": 1665900995.183043,
            "screenshot": true,
            "snapshot": true
        },
        "05 model-not-loaded": {
            "timestamp": 1665901029.4933794,
            "screenshot": true,
            "snapshot": true,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        },
        "06 program-stopped": {
            "timestamp": 1665901054.5596037
        }
    }
}