{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\3dviewer\\snapshots\\ZIP-zbsm\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1665953948.0749722
        },
        "01 program-started": {
            "timestamp": 1665953949.9533896
        },
        "02 program-loaded": {
            "timestamp": 1665953951.5729907
        },
        "03 program-prepared": {
            "timestamp": 1665953956.9513888,
            "screenshot": true,
            "snapshot": true
        },
        "05 model-not-loaded": {
            "timestamp": 1665953974.4902263,
            "screenshot": true,
            "snapshot": true,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        },
        "06 program-stopped": {
            "timestamp": 1665953976.5490046
        }
    }
}