{
    "server_logfile_path": "E:\\3MF-Analyzer\\data\\evaluation\\3dviewer\\snapshots\\GEN-C-AR-VERTEX-Y-0\\local-server.log",
    "states": {
        "00 program-not-started": {
            "timestamp": 1665939947.8975124
        },
        "01 program-started": {
            "timestamp": 1665939949.7761438
        },
        "02 program-loaded": {
            "timestamp": 1665939951.7048283
        },
        "03 program-prepared": {
            "timestamp": 1665939957.1614795,
            "screenshot": true,
            "snapshot": true
        },
        "05 model-not-loaded": {
            "timestamp": 1665939975.0629346,
            "screenshot": true,
            "snapshot": true,
            "related_exception": [
                "<class 'selenium.common.exceptions.WebDriverException'>",
                "An unknown error occurred in the remote end while processing the command.",
                null,
                null
            ]
        },
        "06 program-stopped": {
            "timestamp": 1665939977.1868966
        }
    }
}